#version: "3.8"
#
#services:
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8000:8000"
#    environment:
#      - DB_HOST=db
#      - DB_PORT=3306
#      - DB_NAME=e_commerce_db
#      - DB_USER=root
#      - DB_PASSWORD=mysql_e_commerce123
#    depends_on:
#      - db
#  db:
#    image: mysql:5.7
#    environment:
#      - MYSQL_ROOT_PASSWORD=mysql_e_commerce123
#      - MYSQL_DATABASE=e_commerce_db
#    ports:
#      - "3306:3306"
version: "3.8"

services:
  web:
    build: .
    command: bash -c "python manage.py migrate --verbosity 3 && python create_superuser.py && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=e_commerce_db_final
      - DB_USER=root
      - DB_PASSWORD=mysql_e_commerce1234
      - DJANGO_SUPERUSER_USERNAME=b.chaitanya
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=mysql_e_commerce1234
      - MYSQL_DATABASE=e_commerce_db_final
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 10s
      retries: 5


