# Generated by Django 5.0.4 on 2024-05-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prize', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('bill', models.BooleanField(default=False)),
                ('add_to_cart', models.BooleanField(default=False)),
            ],
        ),
    ]
